### ISSUE TITLE
Registration failing with below error.

### ISSUE THREAD

**Issue by afaridanquah** [EddyVerbruggen/nativescript-app-sync#15]
TypeError: Cannot read property 'length' of null
getShortTypeString
webpack:///~/redux-devtools-inspector/lib/tabs/getItemString.js:54
https://nativescript-codepush-web.herokuapp.com/assets/vendor.js:33441:29
getText
webpack:///~/redux-devtools-inspector/lib/tabs/getItemString.js:153
getItemString
webpack:///~/redux-devtools-inspector/lib/tabs/getItemString.js:176
JSONDiff._this.getItemString
webpack:///~/redux-devtools-inspector/lib/tabs/JSONDiff.js:148
JSONNestedNode.render
webpack:///~/react-json-tree/lib/JSONNestedNode.js:162
https://nativescript-codepush-web.herokuapp.com/assets/vendor.js:89229:21
measureLifeCyclePerf
webpack:///~/react-dom/lib/ReactCompositeComponent.js:73
ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext
webpack:///~/react-dom/lib/ReactCompositeComponent.js:792

**Comment by EddyVerbruggen** [comment]
I am juuuuust in the process of updating this repo. See #14.. this may be related. Hold off a day or 2 plz.

**Comment by dudipsh** [comment]
@EddyVerbruggen 
any updates?

**Comment by EddyVerbruggen** [comment]
I'm not sure what your setup is, but please try with the latest plugin version and make sure to clean your platforms/node_modules/hooks folders when doing so.

If the error persists, please share a Github repo and the commands to trigger the error, then I'm more than happy to take a look.

**Comment by dudipsh** [comment]
@EddyVerbruggen 
Hi, 
It's still happened 
npm i -g nativescript-app-sync-cli
and inside my project, i run 
nativescript-app-sync register

Please login to the browser window we've just opened. If it fails, load this URL in a browser: https://appsync-server.nativescript.org/auth/register?hostname=DESKTOP-00P6R0J

when I click on the link I get a registration page and after 2 sec its redirect to this page 

https://appsync.nativescript.org/register
and i get this error 

```test
TypeError: Cannot read property 'length' of null
getShortTypeString
webpack:///~/redux-devtools-inspector/lib/tabs/getItemString.js:54
https://appsync.nativescript.org/assets/vendor.js:33441:29
getText
webpack:///~/redux-devtools-inspector/lib/tabs/getItemString.js:153
getItemString
webpack:///~/redux-devtools-inspector/lib/tabs/getItemString.js:176
JSONDiff._this.getItemString
webpack:///~/redux-devtools-inspector/lib/tabs/JSONDiff.js:148
JSONNestedNode.render
webpack:///~/react-json-tree/lib/JSONNestedNode.js:162
https://appsync.nativescript.org/assets/vendor.js:89138:21
measureLifeCyclePerf
webpack:///~/react-dom/lib/ReactCompositeComponent.js:73
ReactCompositeComponentWrapper._renderValidatedComponentWithoutOwnerOrContext
webpack:///~/react-dom/lib/ReactCompositeComponent.js:792
```

**Comment by dudipsh** [comment]
Its works with firefox

**Comment by EddyVerbruggen** [comment]
Thanks for reporting back. For now please use a different browser to get past this registration hurdle. We're trying to fix this silly React-built website. Follow along at https://github.com/EddyVerbruggen/nativescript-app-sync-web/issues/2
