### ISSUE TITLE
Can't register, register page throws an error and red-screens

### ISSUE THREAD

**Issue by john-landgrave** [EddyVerbruggen/nativescript-app-sync#19]
First, not sure if this is the right place for this, but I couldn't find another place to 

I attempted to do a `nativescript-app-sync register` this morning and was taken to https://appsync-server.nativescript.org/auth/register?hostname=MY_HOSTNAME_HERE when I was greeted with the following after a brief second:

![image](https://user-images.githubusercontent.com/6320656/60269680-eda81500-98bc-11e9-86ee-e07b3dd35e54.png)

I've tried just hiding that error div, but it looks like the whole react app is crashing, preventing me from registering. I see #7 was closed, but this is still an issue. I tried Edgium, Firefox, and Edge and none of those worked. Chrome let me get to the last step (Step 4, the 🚀), but then it crashed out there and I had to do a `nativescript-app-sync login`and then log in and generate an Access key there.

The error is actually coming from the `react-devtools-inspector` package, and I'm seeing a lot of stuff log that looks like maybe this isn't a production build?

**Comment by EddyVerbruggen** [comment]
Thanks for those details. Really helpful. I’m currently not able to fix it but will soon.

**Comment by max-pro** [comment]
Try to use a different browser. I got the same issue in chrome. then I tried Firefox it's working fine.

**Comment by john-landgrave** [comment]
As I commented, I tried Firefox, Edgium, and Edge before chrome worked. Referencing #7, it seems kind hit or miss.

**Comment by EddyVerbruggen** [comment]
Hmm, @john-landgrave can you please clean your browser cache and try again? I'm failing to see this error in either Chrome (latest) and Safari.

Note that just to be sure the build wasn't corrupted I published a new build.

**Comment by john-landgrave** [comment]
Seems to be working fine now. Tested Edgium, Chrome, and Firefox and all were good.

**Comment by EddyVerbruggen** [comment]
Thx for sharing that!

**Comment by tectiv3** [comment]
nope, not working again (tried chrome, safari and firefox):
After downloading almost 4mb of vendor.js it is crashing with:
```
TypeError: val is null
getShortTypeString
webpack:///~/redux-devtools-inspector/lib/tabs/getItemString.js:54
```

**Comment by EddyVerbruggen** [comment]
@tectiv3 It's very frustrating to me that I can't reproduce it. Do you have any clue how to reproduce and/or fix it at all?

**Comment by tectiv3** [comment]
Well, I am not doing anything special. No requests blocked, but those are the errors in console:
<img width="600" src="https://user-images.githubusercontent.com/1974189/61451865-674f9200-a995-11e9-8bac-40497c1c4e9f.png">

**Comment by EddyVerbruggen** [comment]
@tectiv3 would you mind sharing a quick screengrab video of your browser window when loading the page? I hope that can give me a clue. I would very much appreciate it!

**Comment by tectiv3** [comment]
There is not much to see:
page loads, you can see input for email entering and few seconds later (when vendor.js is loaded) it flashes to red exception screen from the original comment.

**Comment by EddyVerbruggen** [comment]
@tectiv3 That's already more info than I had; since you mention entering email I conclude you're not on the homepage when that happens. There may be more clues for me if you would be so kind to share a quick screengrab of the browser (including the URL bar).

**Comment by tectiv3** [comment]
no, I am on `https://appsync.nativescript.org/register` but I don't get the chance to enter anything:)
Just tried, same thing happens on `https://appsync.nativescript.org/` too.

**Comment by EddyVerbruggen** [comment]
OK, good to know. But still I don't have that error on macOS Mojave running Chrome 75.0.3770.142 (64 bit). Can you *please* share a video with me of your entire browser screen? I understand there's not much to see, but it *may* give me a clue. Without me being able to reproduce this error I can't provide this service to you..

**Comment by EddyVerbruggen** [comment]
Tried here, seems to work fine: https://www.browserling.com/browse/win/7/chrome/75/https%3A%2F%2Fappsync.nativescript.org%2Fregister

There must be some combination of factors leading to this issue. Perhaps Chrome plugins or adblockers (not that there are any ads on this site), or a corporate firewall, or a choppy Internet connection..
