### ISSUE TITLE
Unable to see install metrics

### ISSUE THREAD

**Issue by shiv19** [EddyVerbruggen/nativescript-app-sync#22]
https://appsync.nativescript.org/apps/`appname`/Production

I'm not able to see my install metrics for any of my app-sync releases
![image](https://user-images.githubusercontent.com/9407019/60774043-215b2880-a162-11e9-9b80-d653c316a6ba.png)

**Comment by EddyVerbruggen** [comment]
I don’t want folks to use that web interface beyond registrations and getting an accesskey. Mostly because of issues like this one. There is a command in the CLI though which works, but since I’m not behind a computer rn I can’t look it up easily. So plz check out the commands in /demo/package.json

**Comment by shiv19** [comment]
Got it. Thanks!
