### ISSUE TITLE
Feature Request: Version label in the Sync success callback

### ISSUE THREAD

**Issue by shiv19** [EddyVerbruggen/nativescript-app-sync#23]
I've noticed that all the app-sync updates get published with a label `v1, v2, v3..` and so on,
it would be nice to receive this label as the 2nd parameter on the `AppSync.sync()`'s success callback.

```js
AppSync.sync({ ... }, (syncStatus, updateLabel) => {
  if (syncStatus === SyncStatus.UP_TO_DATE) {
    console.log("AppSync: up to date", updateLabel);
  } else if (syncStatus === SyncStatus.UPDATE_INSTALLED) {
    console.log("AppSync: update installed", updateLabel);
  }
});
```

If not, it would be nice to let the developer pass a version tag during the release that gets returned here.

**Comment by EddyVerbruggen** [comment]
Great idea! The reason it's not there is because of API compatibility with Microsoft CodePush, but an optional second param won't hurt.

**Comment by shiv19** [comment]
Wow, that was quick 😍😍
Thank you!

**Comment by EddyVerbruggen** [comment]
You're welcome. Trying to keep you going with testing this baby 👶.. 🤣
