### ISSUE TITLE
Cannot install app-sync

### ISSUE THREAD

**Issue by lehongwang** [EddyVerbruggen/nativescript-app-sync#25]
i did
tns plugin add nativescript-app-sync
but

npm ERR! path git
npm ERR! code ENOENT
npm ERR! errno ENOENT
npm ERR! syscall spawn git
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/EddyVerbruggen/nativescript-zip.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Quang.LHQ.000\AppData\Roaming\npm-cache\_logs\2019-07-30T02_17_49_691Z-debug.log
Command npm.cmd failed with exit code 1

please help

![2019-07-30_091914](https://user-images.githubusercontent.com/9875802/62095599-1ef47600-b2ab-11e9-941d-ee49ee3117cc.png)

**Comment by EddyVerbruggen** [comment]
The website (git repo) exists (try it in your browser), so perhaps there was a network hickup or a corporate firewall interfering?

**Comment by lehongwang** [comment]
EddyVerbruggen, can you help me to detect if app is on preview mode to not to require app-sync ?
thank you

**Comment by EddyVerbruggen** [comment]
I saw this was answered to you on Slack. Can you please post the solution here and close? Thx.

**Comment by EddyVerbruggen** [comment]
For others: to see if you're running inside the NativeScript Preview app, use https://github.com/EddyVerbruggen/nativescript-appversion to check the current app id, and if it's `org.nativescript.preview` you're running in the Preview app (instead of your app in standalone mode).
