### ISSUE TITLE
what service can we use here?

### ISSUE THREAD

**Issue by jdnichollsc** [EddyVerbruggen/nativescript-app-sync#26]
Hi Eddy,
What service can we use with this plugin? AppCenter?

Thanks in advance, let me know if you need help creating this plugin 👍

**Comment by EddyVerbruggen** [comment]
Hi! There's no additional service you need to use. It should all be pretty clear from the readme in this repo actually; NativeScript is hosting their own "AppCenter"-like service as a backend for this solution, and you interact with it through the NativeScript AppSync CLI (from your computer), and this plugin (from your app).

**Comment by jdnichollsc** [comment]
Ohh yeah, sorry. Later I saw the video, thanks! https://youtu.be/qR1ESQTALI0
