### ISSUE TITLE
The nativescript-app-sync is not compatible with Sidekick iOS cloud build

### ISSUE THREAD

**Issue by miiihi** [EddyVerbruggen/nativescript-app-sync#27]
To recreate: 
1. add the `nativescript-app-sync` to the project (with `tns plugin add nativescript-app-sync`
2. start a cloud iOS build in Sidekick.
3. the build fails on npm install...

The error looks the same as described here https://github.com/NativeScript/sidekick-feedback/issues/288, nativescript-app-sync's postinstall hook is trying to install something into '/usr/local/lib/node_modules', which it is not allowed...

Detailed sidekick log available here https://gist.github.com/miiihi/3967f3ced0210a1d7297fbfebc7e4016

**Comment by EddyVerbruggen** [comment]
I think it's this part of the `postinstall` script: `npm i -g nativescript-app-sync-cli`.

**Comment by EddyVerbruggen** [comment]
Can you give 1.0.4 a spin? I've removed that command as it's already documented in the readme you should run this yourself anyway.

**Comment by miiihi** [comment]
Agree, postinstall hook shouldn't do the global install. Will test soon.

**Comment by miiihi** [comment]
Tested and confirmed as fixed.
And kudos for one of the fastes fixes ever seen! Thanks!

**Comment by EddyVerbruggen** [comment]
And thanks you for the decent issue-report. That helped!
