### ISSUE TITLE
Local App doesn't get updates

### ISSUE THREAD

**Issue by dudipsh** [EddyVerbruggen/nativescript-app-sync#33]
@EddyVerbruggen 
when I change something in my app nothing happens until i comment out this code

```typescript
application.on(application.resumeEvent, () => {
    AppSync.sync({
        deploymentKey: token,
    });
});
```

**Comment by EddyVerbruggen** [comment]
When using livesync / development mode I don't think it's wise to have AppSync activated.

**Comment by dudipsh** [comment]
@EddyVerbruggen 
Thanks for the quick response! 

I understand from you that this is the expected behavior?

The reason I don't want to comment out it is that I'm afraid to forget to return this code before I publish which will make users not get updates anymore

**Comment by EddyVerbruggen** [comment]
Don't you have more changes going on between dev and prod versions of your app? I usually do and tie running this code into that mechanism.

**Comment by dudipsh** [comment]
Usually it's true but, I have a new app and for now, i release versions only for QA.
Anyway, I thought it was a bug
Excellent plugin with or without it
So thanks :)
