### ISSUE TITLE
Images added to App_Resources not synced

### ISSUE THREAD

**Issue by manijak** [EddyVerbruggen/nativescript-app-sync#40]
- CLI: 6.1.2
 - Cross-platform modules: 6.1.1
 - Android Runtime: 6.0.1
 - iOS Runtime: 6.0.1
 - Plugin(s): nativescript-app-sync 1.0.5
 - Xcode 11

Added a new image (.png) to the android & ios App_Resources folder. It worked in the simulator and on device. But after publishing the patch via app-sync, the image did not appear on my device after restarting. Had to upload the image to online service and link it.

**Comment by EddyVerbruggen** [comment]
I think that’s expected behavior as those files are not part of the app bundle, but rather the native resources/assets. If you move those images to fi. app/images you should be fine.

**Comment by manijak** [comment]
Ah didn't know that. The main readme tells us that anything innside the `app` folder is synced.

> What can (and will) be AppSync'ed?
>     Anything inside your /app folder.
>     Anything inside your /node_modules folder.
>

**Comment by EddyVerbruggen** [comment]
Yes, I'll make that more clear then because I didn't mean App_Resources as well (it's not mandatory to have that inside the app folder btw).
