### ISSUE TITLE
Will this work if deployed as an Android App Bundle?

### ISSUE THREAD

**Issue by crowmagnumb** [EddyVerbruggen/nativescript-app-sync#41]
Will this work if you deploy your app as an Android App Bundle or only if deployed as an apk? And can we add that fact (yes or no) to the README so that it is known? Cheers!!

**Comment by EddyVerbruggen** [comment]
I’m not sure because I haven’t tried that. Is it perhaps something you can try?

**Comment by shiv19** [comment]
Yes, it works fine. I use it that way :)

**Comment by crowmagnumb** [comment]
Thanks @shiv19 !
