### ISSUE TITLE
Seemingly unnecessary sub-dependency "properties" causes problems

### ISSUE THREAD

**Issue by crowmagnumb** [EddyVerbruggen/nativescript-app-sync#43]
```
npm i nativescript-app-sync
```
... installs sub-dependency node_module "properties". I have 1.0.6 installed. This node_module then conflicts with running nativescript-app-sync and tns commands for different reasons. For tns there is a require(../properties) line in some code that for some reason imports the "properties" node_module instead of the file from the directory within the nativescript code module. I can't remember the problem using the nativescript-app-sync command but its something similar. At any rate, removing the node_modules/properties directory has no ill effect and solves all my problems. So it seems this is an unnecessary sub-dependency.

Anyone else run into this?

**Comment by EddyVerbruggen** [comment]
I'd love to get rid of it - would you mind doing a PR?

**Comment by crowmagnumb** [comment]
I didn't look too hard but couldn't find where the dependency was coming from.

**Comment by EddyVerbruggen** [comment]
I hope we can see you return one day. I'll look into the dependency, thanks again for the report.

**Comment by EddyVerbruggen** [comment]
@crowmagnumb Just FYI this (removing the `properties` dependency) was fixed in 1.0.7 which was released last week for #42.

**Comment by crowmagnumb** [comment]
Ah cheers! Yeah, I'm not gone for sure, just in a pinch right now to get an app on the store. Thanks for all your work!
