### ISSUE TITLE
Error: Can't resolve '@nativescript/core'

### ISSUE THREAD

**Issue by codytooker** [EddyVerbruggen/nativescript-app-sync#50]
Using Nativescript Vue and adding `nativescript-app-sync`, trying to import AppSync I get the following errors

```
 Can't resolve '@nativescript/core' in '/node_modules/nativescript-app-sync'
 @ ../node_modules/nativescript-app-sync/app-sync.js 9:13-42
```

as well as 

```
ERROR in ../node_modules/nativescript-app-sync/TNSRemotePackage.js
ERROR in ../node_modules/nativescript-app-sync/TNSLocalPackage.js
ERROR in ../node_modules/nativescript-app-sync/TNSAcquisitionManager.js
ERROR in ../node_modules/nativescript-app-sync/TNSRequester.js
```

All with 

```
Module not found: Error: Can't resolve '@nativescript/core'
```

**Comment by EddyVerbruggen** [comment]
Which N version are you using?

**Comment by codytooker** [comment]
`6.2.2`

**Comment by EddyVerbruggen** [comment]
@NathanWalker Do you perhaps have an idea? I'm currently in the middle of moving to a new home with my family and have absolutely no spare time atm..

**Comment by shiv19** [comment]
@codytooker 
Can you upgrade tns core modules to 6.2.3 and try again and let us know if it works?

**Comment by NathanWalker** [comment]
@codytooker its also possible you may need to update your webpack config with latest. Best thing is to often generate a fresh new {N} Vue app with tns cli and just copy the webpack config from that.

**Comment by alexandrepxl** [comment]
@codytooker I was having the same problem. I updated the project to 6.3.0 and it worked!

**Comment by codytooker** [comment]
Was out for holiday break but I will try this in the coming days.  Thank you for the info.

**Comment by codytooker** [comment]
This seems to have fixed the issue.  Currently running into problems with App Sync only working on IOS and not Android but that is an unrelated issue.
